### ISSUE TITLE
[Feature Request] Dyeable Sacks

### ISSUE THREAD

**Issue by CocoManiaDX** [mageowl/sacks-mod#2]
Heya! First of all, thank you for making this standalone mod. It's great to have this feature without needing a mod that adds 100+ things 🙏

Just a thought. Would it be possible to add colored variants of the sacks, like Shulker Boxes?
Mostly so they're easy to differenciate at a glance while on an inventory.

Either way, thanks again and have a good day :)

**Comment by mageowl** [comment]
Thanks for submitting an issue. I've added this feature to version 1.2 on Modrinth.

**Comment by CocoManiaDX** [comment]
Oh wow! Thank you so much! 💖
